name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клон репозиторію
      uses: actions/checkout@v3

    - name: Встановити .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Відновити залежності
      run: dotnet restore

    - name: Надати права на selenium-manager
      run: chmod +x lab3Test/bin/Debug/net6.0/selenium-manager/linux/selenium-manager

    - name: Побудувати рішення
      run: dotnet build --no-restore

    - name: Запустити тести
      run: dotnet test --no-build --verbosity normal
